Mayhem
mayhemheroes/id3v2lib pull request #1
Opened 2022-05-16 03:41 UTC by Jacob-Clemente

2022-07-23 22:45 UTC, xansec requested changes
Please make the requested changes.

2022-07-23 22:45 UTC, xansec commented on fuzz.c
> +#include "id3v2lib.h"
I would recommend changing the name of this file and target to indicate what is actually being fuzzed.

2022-07-25 21:36 UTC, jacobclemente commented
I have made the appropriate changes, but have run into a bit of a snag with getting the action to succeed. I recently changed my Github username to omit a hyphen, and I could not use Mayhem do to a mismatched username. I was unable to change my username on the ForAllSecure website, so I resorted to deleting the old account. I am having trouble signing into my newly created account, linked to my Github.

2022-07-25 21:55 UTC, jacobclemente commented
I have implemented the requested changes to my fork's Mayhem branch.

2022-07-27 02:45 UTC, xansec commented
LGTM!

2022-07-27 02:45 UTC, merged